### PR TITLE
Don't null out the SSL relay nuke directory, otherwise we'll never cleanup the SSL support files.

### LINKED ISSUE #108: SSL support directories not being cleaned up
It looks like BrowserMob Proxy isn't cleaning up the SSL support directories when a proxy is shutdown.  This has resulted in me exhausting inodes several times over the past few weeks.  I've tracked the problem down to one line that seems to have been intentionally inserted and I don't know the history around that.  I'll submit a pull request and maybe someone can weigh in.

### PR DESCRIPTION
**Pull request by nirvdrum**
Fixes #108: SSL support directories not being cleaned up.

@lightbody if you could take a look at this, it'd be much appreciated.  It looks like you explicitly nulled out this directory in a commit about a year ago.  I couldn't garner from context why though.

### CODE REVIEW

**Comment by lightbody** [comment]
This was done to make sure that we could re-establish a connection to that that SSL host very quickly for long-running proxies. So we need to leave the files around until at least when the JVM (or BMP service) is terminated. So  your change is not right either, since it'll lose the fast caching. 

Can you work on a change that won't delete the files when the SocketListener is closed, but will when the proxy itself is terminate or the JVM dies? I had hoped that because we use File.createTempFile this would happen automatically but it doesn't :(

**Comment by nirvdrum** [comment]
I thought that might be why it was done, but when I close the proxy and re-open it, a new set of SSL support files is created anyway.  Any idea why that might be the case?

**Comment by nirvdrum** [comment]
My analysis may be wrong here, but when a proxy is created, a new BrowserMobProxyHandler is created.  This new instance always has a blank SSL map and SSL support directory is created as a temp directory, meaning it has random characters in the directory name.  As a result of the blank map, a new set of support files is created.  As a result of them being temp directories with random chars, they're always written to different locations.  So, I don't see how these files can be used across proxies.  Perhaps that's a separate bug?

**Comment by lightbody** [comment]
You're right: they aren't used across proxies, but they should be!

**Pull request closed without merging**
